#include<iostream>
#include<vector>
using namespace std ;
int main(){
    vector<int>v;
    v.push_back(1);
    v.push_back(5);
    v.push_back(6);
    v.push_back(1);
    v.push_back(5);
    int x=5;
    int idx=-5;
    //---- forward loop
    for(int i=0;i<v.size();i++){
       if(v[i]==x) idx=i;
    }
    cout<<idx;
}
    //---backward---
   // for(int i=v.size()-1;i>=0;i--){
      //  if(v[i]==x){
       //     idx= i;
           // break;
      //  }
  //  }
   // cout<<idx;
//}
